version: '3.5'

services:
  postgres-customer:
    container_name: postgres_customer_container
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres-api-customer}
      PGDATA: /data/postgres
    volumes:
      - postgres_customer:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - customer-network
    restart: unless-stopped

  pgadmin-customer:
    container_name: pgadmin_customer_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_customer:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - customer-network
    restart: unless-stopped

networks:
  customer-network:
    driver: bridge

volumes:
  postgres_customer:
  pgadmin_customer:
