apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-customer-service
spec:
  selector:
    app: {{ .Release.Name }}-customer-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  externalTrafficPolicy: Local
